
[window]
padding = { x = 1, y = 5 }
decorations = "None"
opacity = 0.85

[font]
normal = { family = "FiraCode Nerd Font", style = "Medium" }

[general]
import = [
    "~/.config/alacritty/alacritty-theme/themes/gruvbox_dark.toml"
]
